spring:
  datasource:
    url: jdbc:mysql://localhost:3306/memorized?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug

cloud:
  aws:
    s3:
      bucket: your-s3-bucket-name
    credentials:
      access-key: your-access-key
      secret-key: your-secret-key
    region:
      static: ap-northeast-2
    stack:
      auto: false

# Book API Configuration
book:
  api:
    url: https://www.googleapis.com/books/v1/volumes
    key: ${GOOGLE_BOOKS_API_KEY:} # 환경변수로 설정하거나 직접 입력

jwt:
  secret: "memorized-2025-challkathon-super-secret-key-1234567890!@#%$^&*()_+"
